# Import base URL and content type from environments
@baseUrl = {{$dotenv baseUrl}}
@contentType = {{$dotenv contentType}}

### Get all environments (Azure subscriptions)
# @name getEnvironments
GET {{baseUrl}}/environments
Accept: {{contentType}}

### Get cost analysis for a specific environment
# @name getCostAnalysis
GET {{baseUrl}}/cost-analysis?subscriptionId={{subscriptionId}}
Accept: {{contentType}}

# Variables for request body
@subscriptionId = 00000000-0000-0000-0000-000000000000
